### ISSUE TITLE
Is there a possibility to use dynamic expressions?

### ISSUE THREAD

**Issue by ronilitman** [kasperlewau/angular-bind-notifier#33]
Hi,

For example I have a list and for every item I want to put other expression :

`<ul>
   <li ng-repeat ="item in items" >
     <h1 bind-notifier="{::someEvent + $index:: }">{{item.header}}</h1>
    </li>
</ul>`

Currently I am facing a parse error. Is there a way to make it work?

Thanks

**Comment by kasperlewau** [comment]
Hey Ron. If I'm understanding the question and the given HTML correctly you're attempting to get dynamic keys working for the notifier directive. 

`bind-notifier="{ [dynamic_event_key]: [watch_expression] }"`

This is currently not supported. The notifier expression is evaluated during `compile` time, not during `link` time. Because of that, we do not have access to the underlying value(s) of your expressions - not yet at least. 

https://github.com/kasperlewau/angular-bind-notifier/blob/master/src/bindNotifier.js#L170

Off of the top of my head, I'm not so sure what sort of performance implications we'd be looking at if we defer the parsing until the `link` phase. My best guess is it would be a performance degradation. 

If I understood the usecase better, I might be able to suggest alternatives to get around this limitation. 

I hope that answers your question. Cheers!

**Comment by thSteve** [comment]
This is exactly what I was hoping to achieve with this directive:

I have an ng-repeat of 1000 objects, each of them has ~200 bindings. Any of these can be changed at any time.

I want each row in the repeat to watch the `updated_at` field and update *only* that row if the data changes. Here's a simplified example:

`<div ng-repeat="item in items track by item.id" bind-notifier="{ [item.id] : item.created_at }"> {{ [item.id] : item.name}} </div>`
